/// Flutter icons Mujahidin
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mujahidin
///      fonts:
///       - asset: fonts/Mujahidin.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Logo {
  Logo._();

  static const _kFontFam = 'Logo';

  static const IconData cloud_moon = const IconData(0xe800, fontFamily: _kFontFam); 
  static const IconData cloud_sun = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe80c, fontFamily: _kFontFam); 
  static const IconData moon_1 = const IconData(0xe811, fontFamily: _kFontFam); 
  static const IconData sunrise = const IconData(0xe815, fontFamily: _kFontFam); 
}
